services:
  redis:
    image: docker.io/bitnami/redis:8.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    depends_on:
      - redis