server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: Lax
        max-age: 30d
      timeout: 30d
  forward-headers-strategy: NATIVE

spring:
  application:
    name: techgarden-bff
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: blog
              uri: http://techgarden-blog:8080
              predicates:
                - Path=/blog/**
              filters:
                - RewritePath=/blog/?(?<segment>.*), /$\{segment}
                - TokenRelay=
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://sso.dev.techgarden.gg/realms/techgarden
        registration:
          bff:
            provider: keycloak
            client-id: bff
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
  session:
    store-type: redis
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
logging:
  level:
    org.springframework.web.client.RestClient: TRACE