spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: blog
              uri: http://localhost:8081
              predicates:
                - Path=/blog/**
              filters:
                - RewritePath=/blog/?(?<segment>.*), /$\{segment}
                - TokenRelay=